### ISSUE TITLE
Compile error in generated REST controller due to `filterCustomHeaders = true`

### ISSUE THREAD

**Issue by jeaf-anaptecs** [anaptecs/jeaf-generator#344]
![grafik](https://github.com/user-attachments/assets/d50e6353-2d55-4f87-8faa-6725eab6878b)

**Comment by robinste** [comment]
Probable cause is the class hierarchy of BeanParams.
In the UML model, we have 2 POJOs:

    @BeanParam( supportsCustomHeaders=false )
    OSDMWriteContext extends OSDMContext  
    
    @BeanParam( supportsCustomHeaders=true )
    OSDMContext

The code-generation for the RESTOperation (right-hand side in screenshot) uses [hasParamCustomHeaders](https://github.com/anaptecs/jeaf-generator/blob/8427d773d7f98cfdc69bdd11fc3d669ff382745a/jeaf-generator/src/main/resources/java/GeneratorCommons.ext#L630) which checks the parent class.

The code-generation for the RESTResource (left-hand side) uses [filterCustomHeaders](https://github.com/anaptecs/jeaf-generator/blob/8427d773d7f98cfdc69bdd11fc3d669ff382745a/jeaf-generator/src/main/resources/functions/RESTResource.ext#L13) which **doesn't** check the parent class.

Work-around: Setting `OSDMWriteContext.supportsCustomHeaders = true` fixes the code-gen error,
but creates an ugly subclass that has it own `customHeaders` field, "hiding" the same field in the parent.
